spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/1329154840/config-file.git
          username: 1329154840@qq.com
          password: 858819961221tony
          basedir: src/main/resources/config-file #/home/scp/config-file
          search-paths: client
          clone-on-start: true
          force-pull: true
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
#  instance:
#    prefer-ip-address: true
#    instance-id: 114.115.130.42:${spring.application.name}:${server.port}
server:
  port: 1111
